package com.lanou3g.autohome;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "COLLECT".
 */
public class Collect implements Serializable {

    private Long id;
    private String url;
    private String imageUrl;
    private String title;
    private String time;

    public Collect() {
    }

    public Collect(Long id) {
        this.id = id;
    }

    public Collect(Long id, String url, String imageUrl, String title, String time) {
        this.id = id;
        this.url = url;
        this.imageUrl = imageUrl;
        this.title = title;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
